---
version: "3"
services:
  dineout:
    container_name: dineout-contt
    build: ./dineout
    ports:
      - "1111:80"

  food-delivery:
    container_name: food-deliver-contt
    build: ./food-delivery
    ports:
      - "2222:80"

  genie:
    container_name: genie-contt
    build: ./genie
    ports:
      - "3333:80"

  instamart:
    container_name: instamart-contt
    build: ./instamart
    ports:
      - "4444:80"
