---
version: "3"
services:
  dineout:
    container_name: dineout-container
    build: ./dineout
    ports:
      - "1122:80"

  food-delivery:
    container_name: food-deliver-container
    build: ./food-delivery
    ports:
      - "2233:80"

  genie:
    container_name: genie-container
    build: ./genie
    ports:
      - "3344:80"

  instamart:
    container_name: instamart-container
    build: ./instamart
    ports:
      - "4455:80"
